// 48 World Cup 2026 teams — tla/apiName used for matching football-data.org responses
export const TEAMS = [
  { id:1,  name:'USA',          flag:'🇺🇸', group:'A', tla:'USA', apiName:'United States' },
  { id:2,  name:'Brazil',       flag:'🇧🇷', group:'A', tla:'BRA', apiName:'Brazil' },
  { id:3,  name:'Serbia',       flag:'🇷🇸', group:'A', tla:'SRB', apiName:'Serbia' },
  { id:4,  name:'Morocco',      flag:'🇲🇦', group:'A', tla:'MAR', apiName:'Morocco' },
  { id:5,  name:'Mexico',       flag:'🇲🇽', group:'B', tla:'MEX', apiName:'Mexico' },
  { id:6,  name:'France',       flag:'🇫🇷', group:'B', tla:'FRA', apiName:'France' },
  { id:7,  name:'Poland',       flag:'🇵🇱', group:'B', tla:'POL', apiName:'Poland' },
  { id:8,  name:'Senegal',      flag:'🇸🇳', group:'B', tla:'SEN', apiName:'Senegal' },
  { id:9,  name:'Canada',       flag:'🇨🇦', group:'C', tla:'CAN', apiName:'Canada' },
  { id:10, name:'Spain',        flag:'🇪🇸', group:'C', tla:'ESP', apiName:'Spain' },
  { id:11, name:'Switzerland',  flag:'🇨🇭', group:'C', tla:'SUI', apiName:'Switzerland' },
  { id:12, name:'Japan',        flag:'🇯🇵', group:'C', tla:'JPN', apiName:'Japan' },
  { id:13, name:'Argentina',    flag:'🇦🇷', group:'D', tla:'ARG', apiName:'Argentina' },
  { id:14, name:'Germany',      flag:'🇩🇪', group:'D', tla:'GER', apiName:'Germany' },
  { id:15, name:'Croatia',      flag:'🇭🇷', group:'D', tla:'CRO', apiName:'Croatia' },
  { id:16, name:'South Korea',  flag:'🇰🇷', group:'D', tla:'KOR', apiName:'Korea Republic' },
  { id:17, name:'England',      flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', group:'E', tla:'ENG', apiName:'England' },
  { id:18, name:'Portugal',     flag:'🇵🇹', group:'E', tla:'POR', apiName:'Portugal' },
  { id:19, name:'Denmark',      flag:'🇩🇰', group:'E', tla:'DEN', apiName:'Denmark' },
  { id:20, name:'Australia',    flag:'🇦🇺', group:'E', tla:'AUS', apiName:'Australia' },
  { id:21, name:'Netherlands',  flag:'🇳🇱', group:'F', tla:'NED', apiName:'Netherlands' },
  { id:22, name:'Belgium',      flag:'🇧🇪', group:'F', tla:'BEL', apiName:'Belgium' },
  { id:23, name:'Sweden',       flag:'🇸🇪', group:'F', tla:'SWE', apiName:'Sweden' },
  { id:24, name:'Iran',         flag:'🇮🇷', group:'F', tla:'IRN', apiName:'IR Iran' },
  { id:25, name:'Italy',        flag:'🇮🇹', group:'G', tla:'ITA', apiName:'Italy' },
  { id:26, name:'Turkey',       flag:'🇹🇷', group:'G', tla:'TUR', apiName:'Türkiye' },
  { id:27, name:'Ukraine',      flag:'🇺🇦', group:'G', tla:'UKR', apiName:'Ukraine' },
  { id:28, name:'Nigeria',      flag:'🇳🇬', group:'G', tla:'NGA', apiName:'Nigeria' },
  { id:29, name:'Colombia',     flag:'🇨🇴', group:'H', tla:'COL', apiName:'Colombia' },
  { id:30, name:'Uruguay',      flag:'🇺🇾', group:'H', tla:'URU', apiName:'Uruguay' },
  { id:31, name:'Scotland',     flag:'🏴󠁧󠁢󠁳󠁣󠁴󠁿', group:'H', tla:'SCO', apiName:'Scotland' },
  { id:32, name:'Cameroon',     flag:'🇨🇲', group:'H', tla:'CMR', apiName:'Cameroon' },
  { id:33, name:'Chile',        flag:'🇨🇱', group:'I', tla:'CHI', apiName:'Chile' },
  { id:34, name:'Ecuador',      flag:'🇪🇨', group:'I', tla:'ECU', apiName:'Ecuador' },
  { id:35, name:'Egypt',        flag:'🇪🇬', group:'I', tla:'EGY', apiName:'Egypt' },
  { id:36, name:'Tunisia',      flag:'🇹🇳', group:'I', tla:'TUN', apiName:'Tunisia' },
  { id:37, name:'Paraguay',     flag:'🇵🇾', group:'J', tla:'PAR', apiName:'Paraguay' },
  { id:38, name:'Bolivia',      flag:'🇧🇴', group:'J', tla:'BOL', apiName:'Bolivia' },
  { id:39, name:'Saudi Arabia', flag:'🇸🇦', group:'J', tla:'KSA', apiName:'Saudi Arabia' },
  { id:40, name:'Ghana',        flag:'🇬🇭', group:'J', tla:'GHA', apiName:'Ghana' },
  { id:41, name:'Peru',         flag:'🇵🇪', group:'K', tla:'PER', apiName:'Peru' },
  { id:42, name:'Venezuela',    flag:'🇻🇪', group:'K', tla:'VEN', apiName:'Venezuela' },
  { id:43, name:'Austria',      flag:'🇦🇹', group:'K', tla:'AUT', apiName:'Austria' },
  { id:44, name:'Algeria',      flag:'🇩🇿', group:'K', tla:'ALG', apiName:'Algeria' },
  { id:45, name:'Czech Rep.',   flag:'🇨🇿', group:'L', tla:'CZE', apiName:'Czech Republic' },
  { id:46, name:'Hungary',      flag:'🇭🇺', group:'L', tla:'HUN', apiName:'Hungary' },
  { id:47, name:'Greece',       flag:'🇬🇷', group:'L', tla:'GRE', apiName:'Greece' },
  { id:48, name:'Qatar',        flag:'🇶🇦', group:'L', tla:'QAT', apiName:'Qatar' },
];

export const DEMO_NAMES = [
  'Alice Thompson','Bob Martinez','Charlie Davis','Diana Wilson',
  'Edward Brown','Fiona Taylor','George Anderson','Hannah Jackson',
  'Ivan White','Julia Harris','Kevin Martin','Laura Garcia',
  'Michael Johnson','Natalie Smith','Oliver Jones','Patricia Lee',
  'Quincy Walker','Rachel Hall','Samuel Allen','Tara Young',
  'Umberto King','Victoria Wright','William Scott','Xena Green',
  'Yasmin Baker','Zachary Adams','Amber Nelson','Brian Carter',
  'Carla Mitchell','Derek Perez','Elena Roberts','Frank Turner',
  'Grace Phillips','Henry Campbell','Irene Parker','James Evans',
  'Karen Edwards','Liam Collins','Monica Stewart','Nathan Sanchez',
  'Olivia Morris','Peter Rogers','Quinn Reed','Rebecca Cook',
  'Simon Morgan','Teresa Bell','Victor Murphy','Wendy Bailey',
  'Xavier Rivera','Yvette Cooper',
];

export const CONFETTI_COLORS = [
  '#C41E3A','#C8971C','#F0C040','#2D5A1B','#4A8A2D','#ffffff','#0F1B4C',
];
